In [50]:
import pandas as pd
import re

In [51]:
transactions_df = pd.read_excel("../../data/raw/amonaweri.xlsx", sheet_name="ტრანზაქციები")
transactions_df.drop(columns=["Unnamed: 2"],inplace=True) # drop unneccessary col
 

transactions_df["transaction_type"] = transactions_df["დანიშნულება"].apply(lambda x: x.split()[0]) # separate by transaction type

c:\Users\Saba\.conda\envs\financeAI\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [ ]:
def get_payments_df(transactions_df:pd.DataFrame) -> pd.DataFrame:
    """separates actual payments from just transactions"""
    def find_transaction_object(text):
        pattern = r"ობიექტი:\s*([^,]+)"
        res = re.search(pattern, text)
        if res:
            return res.group(1)

    payments_df = transactions_df.loc[transactions_df["transaction_type"] == "გადახდა"] # separate actal payments from transactions
    payments_df["transaction_object"] = payments_df["დანიშნულება"].apply(lambda x:find_transaction_object(x) ) # separate where transaction was actually performed
    payments_df["transaction_object"] = payments_df["transaction_object"].fillna(value="gadakhda") # fill wherever object was unavailable
    payments_df.drop(columns=["transaction_type"],inplace=True)
    payments_df.fillna(value=0, inplace=True) # fill other NaN values
    return payments_df

,თარიღი,დანიშნულება,GEL,USD,EUR,GBP,transaction_object
2,07/03/2025,"გადახდა - თანხა: GEL2.94; ობიექტი: LIBRE, Tbil...",-2.94,0.0,0.0,0.0,LIBRE
6,09/03/2025,"გადახდა - თანხა GEL3.00; გადახდა, 09/03/2025 ,...",-3.00,0.0,0.0,0.0,gadakhda
12,09/03/2025,"გადახდა - თანხა: GEL5.34; ობიექტი: Nikora, Tbi...",-5.34,0.0,0.0,0.0,Nikora
13,09/03/2025,"გადახდა - თანხა: GEL68.06; ობიექტი: libre, Tbi...",-68.06,0.0,0.0,0.0,libre
14,10/03/2025,გადახდა - თანხა: GEL6.30; ობიექტი: shps gama 2...,-6.30,0.0,0.0,0.0,shps gama 2023
...,...,...,...,...,...,...,...
500,04/03/2026,"გადახდა - თანხა: GEL38.97; ობიექტი: XS Toys, T...",-38.97,0.0,0.0,0.0,XS Toys
501,05/03/2026,"გადახდა - თანხა: GEL3.20; ობიექტი: MAGNITI, Tb...",-3.20,0.0,0.0,0.0,MAGNITI
503,05/03/2026,"გადახდა - თანხა GEL7.00; გადახდა, 05/03/2026 ,...",-7.00,0.0,0.0,0.0,gadakhda
505,05/03/2026,"გადახდა - თანხა: GEL8.20; ობიექტი: ORI NABIJI,...",-8.20,0.0,0.0,0.0,ORI NABIJI
506,06/03/2026,გადახდა - თანხა: GEL3.00; ობიექტი: I/M ZAIRA C...,-3.00,0.0,0.0,0.0,I/M ZAIRA CHICHINADZE

'გადახდა - თანხა: GEL5.34; ობიექტი: Nikora, Tbilisi, tayaishvilis 24; MCC:5411; თარიღი: 08/03/2025 14:41; ბარათის No: ****0301; გადახდის ოპერაციის თანხა და ვალუტა: 5.34 GEL '

,თარიღი,დანიშნულება,GEL,USD,EUR,GBP,transaction_type,transaction_object
2,07/03/2025,"გადახდა - თანხა: GEL2.94; ობიექტი: LIBRE, Tbil...",-2.94,0.0,0.0,0.0,გადახდა,LIBRE
6,09/03/2025,"გადახდა - თანხა GEL3.00; გადახდა, 09/03/2025 ,...",-3.00,0.0,0.0,0.0,გადახდა,gadakhda
12,09/03/2025,"გადახდა - თანხა: GEL5.34; ობიექტი: Nikora, Tbi...",-5.34,0.0,0.0,0.0,გადახდა,Nikora
13,09/03/2025,"გადახდა - თანხა: GEL68.06; ობიექტი: libre, Tbi...",-68.06,0.0,0.0,0.0,გადახდა,libre
14,10/03/2025,გადახდა - თანხა: GEL6.30; ობიექტი: shps gama 2...,-6.30,0.0,0.0,0.0,გადახდა,shps gama 2023
...,...,...,...,...,...,...,...,...
500,04/03/2026,"გადახდა - თანხა: GEL38.97; ობიექტი: XS Toys, T...",-38.97,0.0,0.0,0.0,გადახდა,XS Toys
501,05/03/2026,"გადახდა - თანხა: GEL3.20; ობიექტი: MAGNITI, Tb...",-3.20,0.0,0.0,0.0,გადახდა,MAGNITI
503,05/03/2026,"გადახდა - თანხა GEL7.00; გადახდა, 05/03/2026 ,...",-7.00,0.0,0.0,0.0,გადახდა,gadakhda
505,05/03/2026,"გადახდა - თანხა: GEL8.20; ობიექტი: ORI NABIJI,...",-8.20,0.0,0.0,0.0,გადახდა,ORI NABIJI
506,06/03/2026,გადახდა - თანხა: GEL3.00; ობიექტი: I/M ZAIRA C...,-3.00,0.0,0.0,0.0,გადახდა,I/M ZAIRA CHICHINADZE